# Global protocol parameters
party_count = 4
threshold = 1

# party = <name>, <id>, <host>, <port>
party = party1, 1, party1, 7000
party = party2, 2, party2, 7000
party = party3, 3, party3, 7000
party = party4, 4, party4, 7000
